### ISSUE TITLE
transpiler should support more framework

### ISSUE THREAD

**Issue by junliangtan1** [qBraid/qBraid#215]
### What should we have?

we should support more framework and language, so we can add more simulator for different framework, so we are able to use different tools from different framework. 
adding necessary support for community to add other simulator easily as well.

### Implementation

to implement this, we can learn from https://github.com/PennyLaneAI/PennyLane-qsharp, but we also want to look into tools from other language as well such as julia, c++

**Comment by ryanhill1** [comment]
As per [reddit poll](https://www.reddit.com/r/QuantumComputing/comments/13jorft/which_language_should_qbraid_circuit_transpiler/) seems like OpenQASM 3.0 won the popular vote:

<img width="350" alt="Screenshot 2023-05-18 at 9 47 52 AM" src="https://github.com/qBraid/qBraid/assets/46977852/91c1682a-7f3e-46c7-b616-f231f9c6496e">

### OpenQASM 3.0

The only package that has built-in support for converting to OpenQASM 3.0 seems to be Amazon Braket:
- Amazon Braket $\rightarrow$ OpenQASM 3.0
```python
from braket.circuits import Circuit
from braket.circuits.serialization import IRType

braket_circuit = Circuit().h(0).cnot(0, 1)

qasm3_str = braket_circuit.to_ir(IRType.OPENQASM).source
```

cirq and qiskit both still seem to be hardcoding the openqasm 2 header:
- [cirq QasmParser qasm2 header](https://github.com/quantumlib/Cirq/blob/091688daa8972f13a126d39b737b35e23980394e/cirq-core/cirq/contrib/qasm_import/_parser.py#L135)
- [qiskit QuantumCircuit qasm2 header](https://github.com/Qiskit/qiskit-terra/blob/1d844eccae743032c4416fa67069dbc3478144a9/qiskit/circuit/quantumcircuit.py#L228)

There don't seem to be any packages (yet) that support conversions from OpenQASM 3.0. But will continue to look into it.

Worthwhile approach could be adding converters that convert OpenQASM 2.0 to OpenQASM 3.0 and vice versa.

### Pennylane

As for pennylane, we supported conversion of the `pennylane.tape.QuantumTape` program type in the past. This was pretty straight-forward, because pennylane QuantumTapes have built-in support for converting to/from openqasm, e.g.

```python
import pennylane as qml
from pennylane.tape import QuantumTape
from pennylane.wires import Wires

from qbraid.interface.qbraid_qasm.tools import qasm_num_qubits

with QuantumTape() as tape:
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])

# pennylane to qasm
qasm_str = tape.to_openqasm()

num_wires = qasm_num_qubits(qasm_str)
qml_template = qml.from_qasm(qasm_str)

# pennylane from qasm
with QuantumTape() as tape_out:
    qml_template(wires=Wires(range(num_wires))))
    
```
