### ISSUE TITLE
Keep the qubits order when transpiling circuits to and from all SDKs

### ISSUE THREAD

**Issue by mmlouamri** [qBraid/qBraid#339]
Hello,

qBraid currently flips the qubits order when transpiling Qiskit, Braket, and Pyquil circuits to and from Cirq, and Pytket. Transpilation within these 2 groups {Qiskit, Braket, Pyquil} and {Qiskit, Pytket} preserves the order.

Example: Qiskit to Cirq
```python
from qbraid import circuit_wrapper
from cirq import Circuit as CirqCircuit, H, X, LineQubit
from pytket import Circuit as TketCircuit
from qiskit import QuantumCircuit

# Cirq circuit
qq = LineQubit.range(2)
circ = CirqCircuit()
circ.append(H(qq[0]))
circ.append(X(qq[1]).controlled_by(qq[0]))

print(circ)
```
This outputs
```
0: ───H───@───
          │
1: ───────X───
```
Now transpiling to Qiskit
```python
circuit_wrapper(circ).transpile('qiskit').draw()
```
This outputs
```
          ┌───┐
q_0: ─────┤ X ├
     ┌───┐└─┬─┘
q_1: ┤ H ├──■──
     └───┘     
```

I realize that this is not really a bug but rather the transpiler was designed to reverse qubits in some cases ([using the rev_qubits argument](https://github.com/qBraid/qBraid/blob/main/qbraid/interface/qbraid_cirq/tools.py)). But as a user, I expect the circuits to not get flipped. It is not a major issue but I thought I could open an issue to discuss whether it is a judicious choice to have the qubits flipped.

**Comment by ryanhill1** [comment]
Hey @mmlouamri, thanks for bringing this up. Qubit indicies are sometimes flipped in the circuit drawings because of the different ways the packages index qubits with respect to a given unitary matrix. For the qiskit and cirq circuits you gave above, if you calculated and compared the unitaries, you find find they are equal. But if you instead constructed qiskit and circuit circuits that produced the same circuit drawing, the unitaries would not be equal, e.g.

```python
import numpy as np
from cirq import Circuit, LineQubit, ops
from qiskit import QuantumCircuit
from qiskit.quantum_info import Operator

q0, q1 = LineQubit.range(2)
cirq_circuit = Circuit(ops.H(q0), ops.CNOT(q0, q1))
cirq_unitary = cirq_circuit.unitary()

qiskit_circuit = QuantumCircuit(2)
qiskit_circuit.h(0)
qiskit_circuit.cx(0, 1)
qiskit_unitary = Operator(qiskit_circuit).data

print(cirq_circuit)
print(qiskit_circuit)
print(np.allclose(cirq_unitary, qiskit_unitary)
```
```
0: ───H───@───
          │
1: ───────X───

     ┌───┐     
q_0: ┤ H ├──■──
     └───┘┌─┴─┐
q_1: ─────┤ X ├
          └───┘
          
False
```

So this is where the trade off comes in. We can either (1) choose to maintain equivalence of circuit drawings

<img width="1687" alt="Screenshot 2023-08-10 at 3 23 00 PM" src="https://github.com/qBraid/qBraid/assets/46977852/e6ef5d88-a7f3-4195-b934-c78e6633728d">

Or (2) choose to maintain equivalence of unitaries
<img width="1681" alt="Screenshot 2023-08-10 at 3 23 19 PM" src="https://github.com/qBraid/qBraid/assets/46977852/803db2c9-c6ff-4aa0-b4d0-b7bab937f621">

We initially chose unitaries, but for many, this gets confusing, and the circuit drawing being the same is important. Maybe we could take a poll on our Discord and see what other community members think?
