### ISSUE TITLE
Unable to apply circuit wrapper to Qiskit quantum cicuit

### ISSUE THREAD

**Issue by vprusso** [qBraid/qBraid#544]
### Environment

- **Python version**: 3.10
- **Operating system**: (Amazon Linux 2 operating system)

Relevant Python packages:

```
qbraid==0.5.0
qiskit==0.45.2
qiskit-aer==0.13.2
qiskit-braket-provider==0.0.5
qiskit-terra==0.45.2
```

### What happened?

Attempting to run the following snippet of code:

```py
from qbraid import circuit_wrapper

circuit = QuantumCircuit()
qprogram = circuit_wrapper(qiskit_circuit)
```

Yields:

```
QbraidError: Error applying circuit wrapper to quantum program of type <class 'qiskit.circuit.quantumcircuit.QuantumCircuit'>
```

### What is the expected outcome?

I expect that I should be able to run the `circuit_wrapper` function on a `qiskit.quantumcircuit.QuantumCircuit` object.

### Any suggestions?

Not sure if I'm just using this in a way that is unintended or something else, but any input would be greatly appreciated. Do let me know if I can provide additional details.

**Comment by ryanhill1** [comment]
Hi @vprusso, thanks for raising this issue! I tried applying the `circuit_wrapper` to the empty `qiskit.QuantumCircuit` like you gave above, but was unable the recreate the error:

<img width="764" alt="Screenshot 2024-01-30 at 10 00 13 PM" src="https://github.com/qBraid/qBraid/assets/46977852/5eac8526-743f-4f41-ae10-ab87d249642c">

Could you provide a bit more info about the circuit that you passed to the circuit wrapper, if it wasn't the empty qiskit circuit?

**Comment by vprusso** [comment]
Hi @ryanhill1. Thanks for the quick response. 

Indeed, the circuit was just an empty `Qiskit` quantum circuit. I think the only thing that is potentially reasonable to point out is that I am attempting to run this on the AWS Linux 2 OS via the JupyterLab interface on Amazon. 

Now, I'm not entirely sure why this would be problematic, as I can run other packages on this instance with no problem. So I am a bit stumped as to why this would be an issue. 

Happy to provide more information if helpful.

**Comment by ryanhill1** [comment]
@vprusso This this very interesting. I'm going to attempt to launch my own Amazon Braket notebook instance and see if I can re-create the error. In the mean time, to help us diagnose, could you please try applying the qiskit circuit wrapper directly? If this works, it could be a `pkg_resources` / entrypoints issue. And if not, we'll need to keep investigating. Please try the following:

```python
from qiskit import QuantumCircuit
from qbraid.programs.qiskit import QiskitCircuit

circuit = QuantumCircuit()
qprogram = QiskitCircuit(circuit)
```

**Comment by ryanhill1** [comment]
@vprusso *Update*: I just tested using the Amazon Linux 2 instance and was still unable to re-create the error:

<img width="753" alt="Screenshot 2024-01-30 at 10 37 46 PM" src="https://github.com/qBraid/qBraid/assets/46977852/17e02b2a-4ef0-4260-b8c8-be6fc995b763">


Could you please provide some more specifics about the conditions within which the error occurred? Would love to get this fixed for you ASAP however we can.

**Comment by vprusso** [comment]
Thanks for making the effort to replicate this error. 

It seems like our environments are just about identical. The only difference I see is that I used the `conda_braket` pre-built notebook option. Although I find it odd that this would render the issue I'm seeing. 

I am not sure I can provide any more specifics (at least ones that come to mind) that would be relevant, but if any specific ones come to mind, I'm happy to provide them. 

Thank you again!

**Comment by ryanhill1** [comment]
Hi @vprusso, I tried it out in the `conda_braket` kernel, and I have a theory about what the issue is:

At the top of your notebook, if you installed the packages using the `!` operator, e.g.

```python
!pip install 'qiskit==0.45.2' 'qbraid==0.5.0'
```

then you inadvertently installed the packages into

```
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages
```

However, the `conda_braket` kernel inherits from

```
/home/ec2-user/anaconda3/envs/Braket/lib/python3.10/site-packages
```

To install the packages to the correct location visible to the kernel, you need to use the `%` operator (magic command) e.g.

```python
%pip install 'qiskit==0.45.2' 'qbraid==0.5.0'
```

You can see this effect in action executing

```
!pip --version
```
```
%pip --version
```

in two jupyter notebook cells, and comparing the difference in output. The difference in behavior stems from how the `!` operator executes commands in the shell environment of the Jupyter server, while the `%` magic commands are designed to operate within the context of the IPython kernel's environment. To ensure packages are installed in the correct environment for your Jupyter notebooks, it's generally recommended to use the `%pip` magic command for Python package management within notebooks. See https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pip.

In the video attached below, I use the magic commands within the `conda_braket` notebook to install the packages. I then restart the kernel and run the cells, and things seem to work. Try that out and let me know if that fixes the issue.

https://github.com/qBraid/qBraid/assets/46977852/f14e26ef-5606-4c10-9487-224ca9c16056

**Comment by vprusso** [comment]
Hey @ryanhill1. 

First, I apologize for my delayed response, I was a bit bogged down with other things. 

Next, wanted to say thank you so much for writing up such a comprehensive response. Your solution was spot on and exactly the reason that it was causing an issue. Excellent catch, and thank you again! 

Feel free to close this out, and thank you again for sharing your time and expertise!

**Comment by ryanhill1** [comment]
@vprusso Glad to hear that fixed it, thanks for your interest in the qBraid-SDK!
