### ISSUE TITLE
Working examples for running IBM jobs

### ISSUE THREAD

**Issue by aiotko** [qBraid/qBraid#636]
### Environment

- **qBraid version**: 0.7.0
- **Python version**: 3.11
- **Operating system**: Lab

### What happened?

Sorry for the noobish question, I'm just trying to figure out how to run IBM Quantum jobs, but the example notebooks, as well as tutorials from the documentation, seem to be "deprecated" and aren't working.

```
!qbraid jobs enable qiskit
Usage: qbraid jobs enable [OPTIONS] LIBRARY
Try 'qbraid jobs enable -h' for help.
Invalid value for 'LIBRARY': Library must be one of 'braket'. 
```

```
provider = IBMProvider()
backend = provider.get_backend("ibmq_belem")
AccountNotFoundError: 'No default ibm_quantum account saved.'
```

Could you please point me out how I can run IBM jobs?

**Comment by ryanhill1** [comment]
Hi @aiotko, thanks for raising this issue!

We currently only support managed API access to AWS devices. Unfortunately, we had to withdraw support for IBM devices due to legal issues, but we are actively working with the IBM Quantum team to reinstate access soon. In the meantime, if you would like to use the qBraid-SDK to execute quantum programs on IBM backends, you will need to configure your own IBM credentials. To do so, you can follow the steps provided [here](https://github.com/Qiskit/qiskit-ibm-runtime?tab=readme-ov-file#account-setup).

Thank you for checking out our demo notebooks! We are aware that many of them are outdated and are actively working on updating them to reflect the latest versions of our software and current offerings.

We apologize for the inconvenience regarding IBM support. Please let me know if there is anything else I can assist you with!

**Comment by aiotko** [comment]
Hi @ryanhill1, thank you for your prompt reply!

Could you please clarify the pricing for AWS devices? Is it the same as on Amazon?

Another question about [Forte 1] and, especially, [Aspen-M-3] requiring a reservation.
Would it be possible to use them via qBraid?

**Comment by ryanhill1** [comment]
@aiotko Yes, the pricing is the same as AWS, see https://docs.qbraid.com/projects/lab/en/latest/lab/pricing.html

However, for reservations, you will still need to go through AWS directly. But IonQ Forte-1 is the only device that is currently reservation only.
