### ISSUE TITLE
[FEATURE] List of qbraid_id

### ISSUE THREAD

**Issue by xthecapx** [qBraid/qBraid#833]
### Feature Description

I was trying to locate a list of ID where I can execute my quantum circuit, however, I have not been able to locate one. I tried to use https://github.com/qBraid/QCHack-2022/blob/main/intro_to_qc_challenges/quantum_teleportation/qbraid_sdk.ipynb but most of the IDs returned `ResourceNotFoundError(f"Device '{device_id}' not found.")`

**Comment by ryanhill1** [comment]
Hi @xthecapx, thanks raising this issue! The notebook that you linked dates back to April 2022. Since then, the qBraid-SDK has undergone some significant updates, and the majority of the devices in the "Supported Devices" table from that notebook are now retired.

I would recommend doing a `pip install --upgrade qbraid` to make sure you are using the latest version. Next, I would refer you to our main examples notebooks repository, https://github.com/qBraid/qbraid-lab-demo, particularly the `qbraid_sdk` directory, which was updated very recently, only ~2 weeks ago.

To get all of the devices available to you, simply run:

```python
from qbraid import QbraidProvider

provider = QbraidProvider()

devices = provider.get_devices()

for device in devices:
    print(device.id)
```

Right now, the QuEra, IonQ, NEC, and AWS devices are available through the `QbraidProvider` on a permissions-only basis. However, the `qbraid_qir_simulator` is available to everyone. These other devices will be available to the general public very soon. But in  the mean time, if you'd like to gain early access, feel free to reach out to my at ryanhill@qbraid.com and we can discuss further.
